services:
  advisingapp.local:
    build:
      target: deploy
      args:
        USER_ID: ${SPIN_USER_ID:-9999}
        GROUP_ID: ${SPIN_GROUP_ID:-9999}
    image: 'canyongbs/advisingapp'
    platform: linux/amd64
    ports:
      - '${APP_PORT:-80}:80'
      - '${APP_HTTPS_PORT:-443}:443'
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
