name: Run Renovate

on:
    schedule:
        - cron: '0 11 * * *' # Every day at 11am UTC
    workflow_dispatch:

jobs:
    renovate:
        name: Run Renovate
        runs-on: ubuntu-latest
        timeout-minutes: 15
        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #6.0.2

            - name: Run Renovate
              uses: renovatebot/github-action@8d75b92f43899d483728e9a8a7fd44238020f6e6 #46.1.2
              with:
                  configurationFile: renovate-config.json
                  token: ${{ secrets.PAT }}
