name: Run Renovate

on:
    schedule:
        - cron: '0 11 * * *' # Every day at 11am UTC
    workflow_dispatch:

jobs:
    renovate:
        name: Run Renovate
        runs-on: ubuntu-latest
        timeout-minutes: 15
        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #6.0.2

            - name: Run Renovate
              uses: renovatebot/github-action@e23f4d9675532445118c886434f5a34292b630b4 #46.0.2
              with:
                  configurationFile: renovate-config.json
                  token: ${{ secrets.PAT }}
