name: Run Renovate

on:
    schedule:
        - cron: '0 11 * * *' # Every day at 11am UTC
    workflow_dispatch:

jobs:
    renovate:
        name: Run Renovate
        runs-on: ubuntu-latest
        timeout-minutes: 15
        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #6.0.2

            - name: Run Renovate
              uses: renovatebot/github-action@957af03d760b2c87fc65cb95628f6d5f95d9c578 #46.0.0
              with:
                  configurationFile: .github/renovate.json
                  token: ${{ secrets.PAT }}
